name: dh-arm
channels:
  - conda-forge
dependencies:
  - python>=3.7,<3.10
  - pip
  - tensorflow==2.6.2
  - msgpack-python
  - pandas
  - xgboost
  - llvmlite
  - numba
  - pip:
    - -r requirements.dev.macOS.arm64.txt
